import { Router } from "express";
import { requireAuth } from "../middleware/auth.middleware.js";
import * as c from "../controllers/automation.controller.js";
const r = Router();
r.use(requireAuth);
r.get("/", c.list);
r.post("/", c.create);
r.patch("/:id", c.update);
r.post("/:id/execute", c.execute);
r.get("/:id/executions", c.executions);
export default r;
