import { Router } from "express";
import { requireAuth } from "../middleware/auth.middleware.js";
import * as c from "../controllers/deal.controller.js";
const r = Router();
r.use(requireAuth);
r.get("/", c.listDeals);
r.post("/", c.createDeal);
r.get("/:id", c.getDeal);
r.patch("/:id", c.updateDeal);
r.patch("/:id/move", c.moveDeal);
r.delete("/:id", c.deleteDeal);
export default r;
