import { Router } from "express";
import { requireAuth } from "../middleware/auth.middleware.js";
import { resourceRouter } from "./resource.routes.js";
import { resourceRegistry } from "../utils/resourceRegistry.js";
import * as c from "../controllers/invoice.controller.js";
const base = resourceRouter(resourceRegistry.invoices.service);
const r = Router();
r.use(base);
r.use(requireAuth);
r.patch("/:id/pay", c.markPaid);
r.post("/mark-overdue", c.overdue);
export default r;
